server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_bms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    cn.tedu.fitnessclub: trace