spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
  web:
    resources:
      static-locations: file:${dirPath},classpath:static

mybatis:
  mapper-locations: classpath:mapper/*.xml

knife4j:
  enable: true

dirPath: e:/articlePicture